### ISSUE TITLE
How to use more colors converting from image?

### ISSUE THREAD

**Issue by heruan** [khrome/ascii-art#11]
It is not clear how to use more colors when converting an image to ASCII art. For example, this:

```
$ ascii-art image file.png
```

and this:

```js
var art = require('ascii-art');

var image = new art.Image({
	filepath: 'file.png'
});
image.write(function(err, rendered){
	console.log(rendered);
})
```

produce ASCII art with few colors.

**Comment by khrome** [comment]
It uses color distance to map from the origin colors to terminal colors.
I'm currently working on support for 256 color imagery, which is supported
by many terminals, but not all. Given the current state you can try
1.  increasing the saturation of the image you are putting in or
2.  try to [monkeypatch the color distance function](
https://github.com/khrome/ascii-art/blob/master/image.js#L164) using
`art.Image.distance = <your function>`

**Comment by heruan** [comment]
Thank you for the response! There's no hurry, I'll try the 256 color support when it'll be ready 🙂

**Comment by khrome** [comment]
The [rebuild of ascii-art](https://github.com/khrome/ascii-art/tree/modularization-for-2) is almost ready, but If you'd like to try 256 color support early, use [ascii-art-image](https://github.com/khrome/ascii-art-image), [ascii-art-ansi](https://github.com/khrome/ascii-art-ansi) like so (I'm using ES5 syntax):

```js
var Color = require('ascii-art-ansi/color');
var Image = require('ascii-art-image');
Color.is256 = true; //also supports .isTrueColor if your terminal does
Color.useDistance('closestByIntensity');
var image = new Image({
    width : 80,
    filepath : '/Your/File/Path/To/Image.type',
    alphabet : 'blocks'
});
image.write(function(err, image){
   //image is ready
})
```
Possible alphabets: `variant1`, `variant2`, `variant3`, `variant4`, `ultra-wide`, `wide`, `hatching`, `bits`, `binary`, `greyscale`, `blocks`, `solid`

`Color.useDistance(name);` values are : `euclideanDistance`, `classic`, `ratioDistance`, `classicByValue`, `CIE76Difference`, `closestByIntensity`, `rankedChannel`, `simple`, `original`

On release these options will be built into the call options rather than using the static defaults. Let me know if you encounter any issues.

**Comment by khrome** [comment]
Now documented and published.
